### ISSUE TITLE
Great Post!! How to add Binding Files as Resource?

### ISSUE THREAD

**Issue by NKJamidar** [riha/BtsMsiTask#1]
Hi Riha,

This is a great post and very useful. Thanks for this. 
However, I was trying to add binding file as a resource to MSI. I tried to use "ResourceType.Binding" but was wondering if I want to add multiple binding file for different target environment (i.e. Dev, QA, Production).  

Any suggestions?

**Comment by riha** [comment]
Hi,

Glad you found it useful! It's however currently not supported to add binding files ... Both this and the possibility to add service files are something that we're working on and that will ship in the next version.

Just let me know if there's something else that I can help you with!

**Comment by GuVasudevan** [comment]
We are eagerly waiting for your next release with binding file
