### ISSUE TITLE
The "MsiTask" task was not given a value for the required parameter "DestinationPath".

### ISSUE THREAD

**Issue by ghost** [riha/BtsMsiTask#2]
Hi!
I get this error when trying to run a build and generate a MSI.
I have followed your blog post about this, and can't really figure out whats wrong

**Comment by ghost** [comment]
I am workin in Visual Studio 2013 and this is mu build. proj file 

<Project DefaultTargets="GenerateMsi" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <Import Project="$(MSBuildExtensionsPath)\BtsMsiTask\BtsMsiTask.targets" />
   <PropertyGroup>
      <DestinationPath>$(TF_BUILD_BINARIESDIRECTORY)</DestinationPath>
      <ApplicationName>$(TF_BUILD_BUILDDEFINITIONNAME)</ApplicationName>
   </PropertyGroup>
   <ItemGroup>
      <Resource Include="..\..\bin\BiztalkAutomatedDeployTest.Helper.dll" />
      <BtsAssembly Include="..\..\bin\BiztalkAutomatedDeployTest.Orchestrations" />
      <BtsAssembly Include="..\..\BiztalkAutomatedDeployTest.Schemas.dll" />
      <BtsAssembly Include="..\..\bin\BiztalkAutomatedDeployTest.Pipelines.dll" />
      <BtsAssembly Include="..\..\bin\BiztalkAutomatedDeployTest.Maps.dll" />
   </ItemGroup>

   <Target Name="GenerateMsi">
      <MsiTask  Version="1.0.0.0"
                DestinationPath="$(DestinationPath)"
                ApplicationName="$(ApplicationName)"
                BtsAssemblies="@(BtsAssembly)"
                Resources="@(Resource)" />
   </Target>
</Project>

**Comment by riha** [comment]
Can you show me the complete proj file?
